// <auto-generated />
using System;
using AggilleDFe.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AggilleDFe.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724193632_AdicionarHoraInicialHoraFinalEmpresa")]
    partial class AdicionarHoraInicialHoraFinalEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AggilleDFe.Domain.Entities.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiAtiva")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("API_ATIVA");

                    b.Property<string>("CnpjEmpresa")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("CNPJ_EMPRESA");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("NOME_EMPRESA");

                    b.Property<int?>("PortaApi")
                        .HasColumnType("integer")
                        .HasColumnName("PORTA_API");

                    b.Property<string>("ProcessarIndividualmente")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("PROCESSAR_INDIVIDUALMENTE");

                    b.Property<int?>("QuantidadeEmpresasPermitidas")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_EMPRESAS_PERMITIDAS");

                    b.Property<string>("SenhaApi")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SENHA_API");

                    b.Property<int?>("TempoExecucao")
                        .HasColumnType("integer")
                        .HasColumnName("TEMPO_EXECUCAO");

                    b.Property<string>("UsuarioApi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USUARIO_API");

                    b.Property<int?>("VersaoBanco")
                        .HasColumnType("integer")
                        .HasColumnName("VERSAO_BANCO");

                    b.HasKey("Id");

                    b.ToTable("CONFIGURACAO", (string)null);
                });

            modelBuilder.Entity("AggilleDFe.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambiente")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("AMBIENTE");

                    b.Property<string>("CertificadoDigital")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("CERTIFICADO_DIGITAL");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("EmailEnvioNotificacoes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("EMAIL_ENVIO_NOTIFICACOES");

                    b.Property<string>("EmailPop")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("EMAIL_POP");

                    b.Property<string>("EmailSmtp")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("EMAIL_SMTP");

                    b.Property<TimeOnly?>("HoraFinal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("HORA_FINAL");

                    b.Property<TimeOnly?>("HoraInicial")
                        .HasColumnType("time without time zone")
                        .HasColumnName("HORA_INICIAL");

                    b.Property<string>("Ie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("IE");

                    b.Property<string>("Inativo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("INATIVO");

                    b.Property<int?>("IntervaloTentativas")
                        .HasColumnType("integer")
                        .HasColumnName("INTERVALO_TENTATIVAS");

                    b.Property<string>("Manifesta")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("MANIFESTA");

                    b.Property<string>("PastaXml")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("PASTA_XML");

                    b.Property<int?>("PortaPop")
                        .HasColumnType("integer")
                        .HasColumnName("PORTA_POP");

                    b.Property<int?>("PortaSmtp")
                        .HasColumnType("integer")
                        .HasColumnName("PORTA_SMTP");

                    b.Property<int?>("Posicao")
                        .HasColumnType("integer")
                        .HasColumnName("POSICAO");

                    b.Property<int?>("QuantidadeTentativas")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_TENTATIVAS");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("SenhaCertificado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SENHA_CERTIFICADO");

                    b.Property<string>("SenhaPop")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SENHA_POP");

                    b.Property<string>("SenhaSmtp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SENHA_SMTP");

                    b.Property<string>("ServidorPop")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("SERVIDOR_POP");

                    b.Property<string>("ServidorSmtp")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("SERVIDOR_SMTP");

                    b.Property<int?>("TempoRetorno")
                        .HasColumnType("integer")
                        .HasColumnName("TEMPO_RETORNO");

                    b.Property<int?>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("TIMEOUT");

                    b.Property<int?>("TipoAutenticacaoPop")
                        .HasColumnType("integer")
                        .HasColumnName("TIPO_AUTENTICACAO_POP");

                    b.Property<int?>("TipoAutenticacaoSmtp")
                        .HasColumnType("integer")
                        .HasColumnName("TIPO_AUTENTICACAO_SMTP");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("UF");

                    b.Property<int?>("UltimoNsu")
                        .HasColumnType("integer")
                        .HasColumnName("ULTIMO_NSU");

                    b.Property<int?>("UltimoNsuCte")
                        .HasColumnType("integer")
                        .HasColumnName("ULTIMO_NSU_CTE");

                    b.Property<string>("UsuarioPop")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USUARIO_POP");

                    b.Property<string>("UsuarioSmtp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USUARIO_SMTP");

                    b.HasKey("Id");

                    b.ToTable("EMPRESAS", (string)null);
                });

            modelBuilder.Entity("AggilleDFe.Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("CHAVE");

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("DATA");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<TimeOnly?>("HoraFinal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("HORA_FINAL");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("HORA_INICIO");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text")
                        .HasColumnName("MENSAGEM");

                    b.Property<int?>("QuantidadeXmls")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_XMLS");

                    b.Property<int?>("XmlId")
                        .HasColumnType("integer")
                        .HasColumnName("XML_ID");

                    b.HasKey("Id");

                    b.ToTable("LOGS", (string)null);
                });

            modelBuilder.Entity("AggilleDFe.Domain.Entities.Xml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cancelada")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("CANCELADA");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("CHAVE");

                    b.Property<DateOnly?>("DataCancelamento")
                        .HasColumnType("date")
                        .HasColumnName("DATA_CANCELAMENTO");

                    b.Property<DateOnly?>("DataCiencia")
                        .HasColumnType("date")
                        .HasColumnName("DATA_CIENCIA");

                    b.Property<DateOnly?>("DataDesconhecimento")
                        .HasColumnType("date")
                        .HasColumnName("DATA_DESCONHECIMENTO");

                    b.Property<DateOnly?>("DataDownload")
                        .HasColumnType("date")
                        .HasColumnName("DATA_DOWNLOAD");

                    b.Property<DateOnly?>("DataNaoRealizacao")
                        .HasColumnType("date")
                        .HasColumnName("DATA_NAO_REALIZACAO");

                    b.Property<DateOnly?>("DataRealizacao")
                        .HasColumnType("date")
                        .HasColumnName("DATA_REALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateOnly?>("Emissao")
                        .HasColumnType("date")
                        .HasColumnName("EMISSAO");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("FornecedorCidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FORNECEDOR_CIDADE");

                    b.Property<string>("FornecedorCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("FORNECEDOR_CNPJ");

                    b.Property<string>("FornecedorNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FORNECEDOR_NOME");

                    b.Property<string>("FornecedorUf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("FORNECEDOR_UF");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("MensagemNfe")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("MENSAGEM_NFE");

                    b.Property<string>("Modelo")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("MODELO");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("MOTIVO_CANCELAMENTO");

                    b.Property<string>("MotivoNaoRealizacao")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("MOTIVO_NAO_REALIZACAO");

                    b.Property<string>("NomeXml")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("NOME_XML");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PROTOCOLO");

                    b.Property<string>("Schema")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SCHEMA");

                    b.Property<string>("Serie")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("SERIE");

                    b.Property<string>("Situacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SITUACAO");

                    b.Property<int?>("StatusNfe")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_NFE");

                    b.Property<decimal?>("ValorIcms")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("VALOR_ICMS");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.ToTable("XMLS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
